---
ca_expiry: 8760h
ca_algo: rsa
ca_size: 2048
ca_CN: Kubernetes
ca_C: US
ca_L: New York
ca_O: Kubernetes
ca_OU: NY
ca_ST: Clifton Park


template_dir: "{{ project_root_dir }}/roles/provisionCerts/templates"

clusterName: kubernetes-the-hard-way
