---
#MAINTAINED BY ANSIBLE.
#Changes made here will be over-written.

wFiles:
  - k8-w1.pem
  - k8-w1-key.pem
  - k8-w1.kubeconfig
  - ca.pem
  - kube-proxy.kubeconfig

workerName: k8-w1
workerIP: 192.168.1.25
