---
- name: Distibuting Worker files
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: ~/
  loop: "{{ wFiles }}"
  when:
    - inventory_hostname in groups['Worker']

- name: Distibuting Controller files
  copy:
    src: "{{ cert_dir }}/{{ item }}"
    dest: ~/
  loop: "{{ wFiles }}"
  when:
    - inventory_hostname in groups['Master']


