---
- name: Deleting Newtwork Plugin
  k8s:
    state: absent
    force: yes
    namespace: kube-system
    kubeconfig: "~/admin.kubeconfig"
    definition: "{{ lookup('file', '{{ files_dir }}/weave-daemonset-k8s-1.7.yaml') }}"
  when: inventory_hostname == groups.Master[0]

#- name: Deleting Kube-DNS
#  k8s:
#    state: absent
#    kubeconfig: "~/admin.kubeconfig"
#    definition: "{{ lookup('file', '{{ files_dir }}/kube-dns.yml') }}"
#  when: inventory_hostname == groups.Master[0]
